### ISSUE TITLE
Docker image does not write to stdout

### ISSUE THREAD

**Issue by toxuin** [ruippeixotog/ebay-snipe-server#9]
Hi,

I've noticed the docker container runs silent and writes logs to it's internal log file.

This is not really cool since it prevents other log drivers to be used, also this hides all output when running as part of docker-compose stack.

To fix this, I had to create my own Dockerfile and use this as a base image.

I've added one simple command to it and everything runs great:
`RUN mkdir -p /opt/docker/logs && ln -sf /dev/stdout /opt/docker/logs/app.log`

If you could incorporate this logic into the base image that would be very cool.

Thanks!

**Comment by ruippeixotog** [comment]
Good idea! Updated the logging config to output to stdout in c89b743a7 and released version v0.2.1 as a Docker image.
